#!/bin/sh
echo "Loading the software on the net..."

motelist -c | while read line
do
	#[ -z "$line" ] && exit
	if [ "$line" = "No devices found." ]
	then
	  echo "Devices not connected."
	  exit
	fi
	code=`echo $line | cut -d "," -f 1`
	dev=`echo $line | cut -d "," -f 2`
	cat ../sensnet-topology | while read t_line
		do
			t_address=`echo $t_line |cut -d "," -f 1`
			t_code=`echo $t_line |cut -d "," -f 2`
			t_x_coord=`echo $t_line | cut -d "," -f 3`
			t_y_coord=`echo $t_line | cut -d "," -f 4`
			t_z_coord=`echo $t_line | cut -d "," -f 5`
			if [ $code = $t_code ];
			then
				echo "$code, $t_address, $dev, $t_x_coord, $t_y_coord, $t_z_coord"				
				X_COORD=$t_x_coord Y_COORD=$t_y_coord Z_COORD=$t_z_coord make telosb install,$t_address bsl,$dev
			fi
			
		done
done
